### ISSUE TITLE
Hiding of Navigation bar not working properly

### ISSUE THREAD

**Issue by bovillaios** [dimix/ImageSlideShow#10]
Hi Team,

Thanks a lot for the framework. It made my day.

In the below cases, navigation bar is not hidden properly

1. According to the code, for the first swipe, only the navigation bar should be hidden. But it is hidden for the second swipe
2. On image click, if the navigation bar is hidden we are showing the navigation bar. vice-versa is not happening

Can you please look into the above points and do needful.
Thanks,
Ramgopal

**Comment by bovillaios** [comment]
Got an answer for this

In `func setNavigationBar(visible:Bool)`

In the completion block of animation, we need to write the below code (hide the navigation bar again)

`                self.navigationController?.navigationBar.alpha = (visible ? 1.0 : 0.0)
`
Thanks,
Ram

**Comment by dimix** [comment]
Hi, I'm working on the fix. Thanks!
