### ISSUE TITLE
warning: could not execute support code to read Objective-C class data in the process. This may reduce the quality of type information available.

### ISSUE THREAD

**Issue by NikunjGodhani** [dimix/ImageSlideShow#9]
Hi,
I hope you are doing well.
I used this library in my project. I am appending 604 images. App is working perfectly on simulator but on real device it's not working.

warning: could not execute support code to read Objective-C class data in the process. This may reduce the quality of type information available.

App crashing in for loop of PhotoSliderView.Swift

 for (index, image) in images.enumerated()
        {
            let imageView = UIImageView(frame: CGRect(x: scrollViewWidth * CGFloat(index),
                                                      y: 0,
                                                      width: scrollViewWidth,
                                                      height: scrollViewHeight))
            imageView.image = image
            imageView.contentMode = scaleAspectFill
            imageView.clipsToBounds = true
            scrollView.addSubview(imageView)
        }

Help me if you have solution.

**Comment by dimix** [comment]
Why are you creating a PhotoSliderView?
ImageSlideShow is based on PageViewController just to have no memory and performances problems.

**Comment by NikunjGodhani** [comment]
![Ss2](https://user-images.githubusercontent.com/14305975/65335309-d50c7a00-dbe1-11e9-9b07-be5504ac16cb.png)
![Ss1](https://user-images.githubusercontent.com/14305975/65335313-d5a51080-dbe1-11e9-97d1-273dee30d8ca.png)

I am using your library for display photo images. There are 604 Images. App is crashing when I run on device. It's working perfectly on simulator.

**Comment by NikunjGodhani** [comment]
var i = 604
        while(i>=0)
        {
            self.images.append(UIImage(named: "img\(i).jpg")!)
            i = i - 1
        }
        
        self.photoSliderView.configure(with: self.images)
        loaderhiden()
        
      
        NotificationCenter.default.addObserver(self, selector: #selector(self.methodOfReceivedNotification(notification:)), name: Notification.Name("NotificationIdentifier"), object: nil)

**Comment by NikunjGodhani** [comment]
App is crashing when photo slider configure.

 for (index, image) in images.enumerated()
        {
            let imageView = UIImageView(frame: CGRect(x: scrollViewWidth * CGFloat(index),
                                                      y: 0,
                                                      width: scrollViewWidth,
                                                      height: scrollViewHeight))
            imageView.image = image
            imageView.contentMode = .center//.scaleAspectFill//.scaleAspectFit//.scaleAspectFill
            imageView.clipsToBounds = true
            scrollView.addSubview(imageView)
        }

**Comment by dimix** [comment]
Are you sure you are using https://github.com/dimix/ImageSlideShow?
There is no of your posted code in the library..
